### ISSUE TITLE
fix: computed property hydration doesn't work with useFetch

### ISSUE THREAD

**Issue by andrzejewsky** [nuxt-community/composition-api#207] opened 2020-08-17 14:46 UTC
**🐛 The bug**
The computed property it's not being hydrated properly because computed is readonly, so when we return that property in the `setup` (along with useFetch) it will cause a mismatch as `nuxt` wasn't able to assign the value

**🛠️ To reproduce**

```js
const posts = ref(null);
const allPosts = computed(() => posts.value);

useFetch(async () => {
  posts.value  = ....
})

return { allPosts }; // that can't be hydrated
```
**DEMO: https://codesandbox.io/s/sweet-leftpad-kdhl1**

**ℹ️ Additional context**
I think this line is responsible for this: https://github.com/nuxt-community/composition-api/blob/main/src/fetch.ts#L266 - it needs somehow distinguish what kind of property we have and figure out what to do if it's computed.

**Comment by danielroe** [comment] 2020-08-17 15:11
See https://github.com/nuxt-community/composition-api/issues/19 for some context - and https://github.com/vuejs/composition-api/issues/445 for a potential solution...

**Comment by danielroe** [comment] 2020-08-17 16:42
For a temporary workaround, try returning posts from the setup function too...

**Comment by andrzejewsky** [comment] 2020-08-18 14:32
> For a temporary workaround, try returning posts from the setup function too...

that totally won't work... `posts` is just example, we have more complex computed properties in the `setup`, so seems like this plugin is not ready to use, it will work only with simple refs. I've been even trying to solve it in nuxt itself but it's not easy..

**Comment by danielroe** [comment] 2020-08-18 16:12
@andrzejewsky Sorry that did't work for you as a workaround.

The issue is that the fetch mechanism in Nuxt isn't really designed for the Composition API. It's designed to only overwrite what is on the component instance. But with a Composition API workflow, you might have lots of things that aren't on the instance. So `useFetch` won't work for the kind of complex use-case you're thinking of - at least until Nuxt 3 comes out.

However, there are a lot of alternative approaches that **do** work right now. For example, you could use something like `useStatic` or `useAsync`. Or you could use your own mechanism - like defining posts as an `ssrRef` and running your own `serverPrefetch`. Take a look at the docs and feel do free to get in touch on Discord if you have any questions.

I'm closing this as an issue because it's a limitation of the way fetch works rather than a bug, but I appreciate it's frustrating that it didn't work for you - and do feel free to open a new one if you encounter any other issues!

**Closed by danielroe** 2020-08-18 16:12 UTC
Labels: bug

**Comment by andrzejewsky** [comment] 2020-08-18 16:59
@danielroe it's totally understandable, I went through the code and I know what you mean, also I spent hours of thinking about how to solve that as was considering a PR with fixing this, but it's tough as there is no way to make computed assignable. In vue3 we have effects so it's somehow possible, I think we just have to wait - thanks for your help!

**Comment by Sara2009** [comment] 2021-05-19 06:05
> **🐛 The bug**
> The computed property it's not being hydrated properly because computed is readonly, so when we return that property in the `setup` (along with useFetch) it will cause a mismatch as `nuxt` wasn't able to assign the value
> 
> **🛠️ To reproduce**
> Steps to reproduce the behavior:
> 
> ```js
> const posts = ref(null);
> const allPosts = computed(() => posts.value);
> 
> useFetch(async () => {
>   posts.value  = ....
> })
> 
> return { allPosts }; // that can't be hydrated
> ```
> 
> **DEMO: https://codesandbox.io/s/sweet-leftpad-kdhl1**
> 
> **ℹ️ Additional context**
> I think this line is responsible for this: https://github.com/nuxt-community/composition-api/blob/main/src/fetch.ts#L266 - it needs somehow distinguish what kind of property we have and figure out what to do if it's computed.

I found this works. It is a right solution?
```js
const posts = ref(null);

// writable 
// function computed<T>(options: { get: () => T; set: (value: T) => void }): Ref<T>
const allPosts = computed({
  get: () => posts.value,
  set: val => { allPosts.value = val; }, 
});

useFetch(async () => {
  posts.value  = ....
})

return { allPosts }; // that can't be hydrated
```

**Comment by danielroe** [comment] 2021-05-19 19:08
@Sara2009 Yes, it looks like that works 👍

**Comment by stefvw93** [comment] 2021-07-09 13:42
The useFetch + computed property combination was too common to avoid for me, so I wrote a utility function to get around this issue.

It uses a shadow ref for the computed value and keeps a reference to the getter parameter to check if the setter function has been called already. If it has, it will do nothing and output a warning to the console.

```typescript
import {
  computed,
  ComputedGetter,
  ref,
  WritableComputedRef,
} from '@nuxtjs/composition-api';

const getterMap = new Map<ComputedGetter<any>, any>();

/**
 * Takes a getter function and returns an immutable reactive ref object for the returned value from the getter.
 * @param getter
 * @returns
 */
export function ssrComputed<T>(
  getter: ComputedGetter<T>,
): ComputedGetter<T> | WritableComputedRef<T> {
  if (process.server) {
    return computed(getter);
  }

  const shadowRef = ref<any>(getter());

  return computed<T>({
    get: () => shadowRef.value,
    set: (value: any) => {
      if (getterMap.get(getter) ?? false) {
        console.error(
          'Write operation failed: computed value is readonly after hydration.',
        );
      } else {
        // allow writing once, for nuxt SSR hydration
        getterMap.set(getter, true);
        shadowRef.value = value;
      }
    },
  });
}

```
