### ISSUE TITLE
help: why useAsync run both server and clien?

### ISSUE THREAD

**Issue by luchanan** [nuxt-community/composition-api#493] opened 2021-05-31 03:46 UTC
Hi, i ask some quesion, this code run only on server

```
import { defineComponent, useAsync, useContext } from '@nuxtjs/composition-api'

export default defineComponent({
  setup() {
    const { $http } = useContext()
    const posts = useAsync(() => $http.$get('https://jsonplaceholder.typicode.com/posts'))

    return { posts }
  },
})
```

i want to add try catch in my code like this

```
<template>
  <div class="container">
    <div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, useContext, useAsync, reactive, toRefs } from "@nuxtjs/composition-api";
export default defineComponent({
  setup() {
    const {$axios} = useContext()
    const posts = useAsync(async () : Promise<any> => {
      await $axios.$get('https://jsonplaceholder.typicode.com/posts').then(res => {
        console.log(res, '')
      }).catch(res => {
        console.log(res, 'error')
      })
    })
    return { 
     }
  }
});
</script>


```

but, run server and client

**Comment by danielroe** [comment] 2021-08-20 05:20
Probably it runs twice because the second inline function doesn't return anything.

**Comment by MateiNenciu** [comment] 2022-06-11 09:17
It runs twice every time, even some simple code like:
`useAsync(async() => {
      await new Promise(resolve => setTimeout(resolve, 7000))
      console.log('useAsync fired')
      return true
 })` gets executed twice. We are missing something? You said in other issue that we should use this method instead of useFetch if we need to modify store on initial load. But useAsync execute twice so this is still not a solution.

**Comment by danielroe** [comment] 2022-06-19 21:05
I can't reproduce this @MateiNenciu (see https://codesandbox.io/s/elastic-leftpad-f77ms3?file=/pages/index.vue). My best guess is that you have some kind of hydration error (or other error) that is triggering this.

I'm closing this but feel free to provide a reproduction and I'll take a look.

**Closed by danielroe** 2022-06-19 21:05 UTC

**Comment by mango-martin** [comment] 2022-08-06 05:06
@danielroe 
It seems to not work when an error is being caught.
I've edited your [codesandbox](https://codesandbox.io/s/staging-thunder-mje2d7?file=/pages/index.vue)

This runs once
```
const data = useAsync(async () => {
  console.log("useAsync fired");
  try {
    await new Promise((resolve) => setTimeout(resolve, 7000));
    return true;
  } catch {
    return false;
  }
});
```

This runs twice
```
const data = useAsync(async () => {
  console.log("useAsync fired");
  try {
    throw new Error();
  } catch {
    return false;
  }
});
```

Is this by design?

**Comment by mango-martin** [comment] 2022-08-06 05:55
I've looked at the source code and found out why this happens.

The if clause that checks whether to run the cb or not checks for any falsy value. So whenever you return `null | undefined | false | ''` it will run again.

I think it's a bit limiting in design. How about changing this check:
```
if (
    !_ref.value ||
    (process.env.NODE_ENV === 'development' &&
      process.client &&
      window[globalNuxt]?.context.isHMR)
  )
```
to
```
if (
    _ref.value === null ||
    (process.env.NODE_ENV === 'development' &&
      process.client &&
      window[globalNuxt]?.context.isHMR)
  )
```

It still limits in that you cannot return null.
A workaround would be to just add a flag that checks if the server has already run the call or not.
```
const hasRun = ref(false)

if (!hasRun || ...)
```
What do you think?
