### ISSUE TITLE
help: Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,

### ISSUE THREAD

**Issue by jankaderabek** [nuxt-community/composition-api#190] opened 2020-08-07 08:16 UTC
**📚 What are you trying to do? Please describe.**
I have a Nuxt 2.13.3 app and I would like to use nuxt/composition-api, but when i'm trying to build the app, it failed on the following error:
```
ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
```
babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
```
See https://babeljs.io/docs/en/options#filename for more information. (While processing: "/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/nuxt-composition-api/lib/babel.js")
    at validateIfOptionNeedsFilename (/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/@babel/core/lib/config/full.js:274:11)
    at /Users/jankaderabek/xxx/yyy/apps/admin/node_modules/@babel/core/lib/config/full.js:286:52
    at Array.forEach (<anonymous>)
    at validatePreset (/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/@babel/core/lib/config/full.js:286:25)
    at loadPresetDescriptor (/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/@babel/core/lib/config/full.js:293:3)
    at loadPresetDescriptor.next (<anonymous>)
    at recurseDescriptors (/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/@babel/core/lib/config/full.js:107:30)
    at recurseDescriptors.next (<anonymous>)
    at loadFullConfig (/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/@babel/core/lib/config/full.js:142:6)
    at loadFullConfig.next (<anonymous>)
    at Function.<anonymous> (/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/@babel/core/lib/config/index.js:33:43)
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/gensync/index.js:244:28)
    at Function.sync (/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/gensync/index.js:84:14)
    at /Users/jankaderabek/xxx/yyy/apps/admin/node_modules/@babel/core/lib/config/index.js:43:61
    at ssrRefPlugin (/Users/jankaderabek/xxx/yyy/apps/admin/node_modules/nuxt-composition-api/lib/babel.js:9:39)
 @ multi ./.nuxt/client.js app[0]

```
buildModules:
```
  buildModules: [
    '@nuxt/typescript-build',
    'nuxt-composition-api',
  ],
```

Do you have any tips how to solve this problem?

**Comment by danielroe** [comment] 2020-08-07 08:20
@jankaderabek Thanks for the report :heart: Could you create a minimal reproduction?

**Comment by danielroe** [comment] 2020-10-09 22:33
I'm closing this as I don't have a repro to investigate - but feel free to let me know if you get a chance and I'll reopen :slightly_smiling_face:

**Closed by danielroe** 2020-10-09 22:33 UTC
Labels: needs-repro

**Comment by treebee** [comment] 2021-04-23 19:57
Had the same issue, in my case it was a `babel.config.js` I created for Jest + TypeScript like documented [here](https://jestjs.io/docs/getting-started#using-typescript)

I resolved it by rewriting `babel.config.js`, see `Making your Babel config jest-aware` of the [Jest docs](https://jestjs.io/docs/getting-started#using-babel)

Hope this helps in case anyone else stumbles over this.

**Comment by dncdrn** [comment] 2022-02-24 04:15
I have the same issue, but @treebee solution unfortunately doesn't work for me. I'm using Nuxt 2.14.3

Here's what my package.json looks like
` "dependencies": {
    "@nuxtjs/axios": "^5.4.1",
    "downloadjs": "^1.4.7",
    "echarts": "^5.3.0",
    "lodash.isequal": "^4.5.0",
    "nuxt": "^2.14.3",
    "nuxt-i18n": "^6.1.3",
    "vue-cookies": "^1.5.13",
    "vue-echarts": "^6.0.2",
    "vuedashboarq": "^1.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@babel/preset-env": "^7.16.11",
    "@babel/preset-typescript": "^7.16.7",
    "@intlify/vue-i18n-loader": "^0.6.1",
    "@nuxtjs/composition-api": "^0.32.0",
    "@nuxtjs/vuetify": "^1.11.2",
    "@vue/babel-preset-app": "^4.5.6",
    "@vue/composition-api": "^1.4.6",
    "babel-jest": "^24.9.0",
    "babel-preset-env": "^1.7.0",
    "core-js": "^3.5.0",
    "jest": "^24.8.0",
    "sass-loader": "^10",
    "vue-jest": "^3.0.4"
  },
  "babel": {
    "presets": [
      [
        "@babel/preset-env",
        {
          "targets": {
            "node": "current"
          }
        }
      ],
      "@babel/preset-typescript"      
    ]
  },
  "jest": {
    "transform": {
      "^.+.vue$": "vue-jest",
      "^.+.js$": "babel-jest"
    },
    "roots": [
      "<rootDir>/tests/"
    ]
  }`

And this is my nuxt config
`  buildModules: ["@nuxtjs/composition-api/module"],
  /*
   ** Build configuration
   */
  build: {
    transpile: [/echarts/],
    // Fix related to core-js@3
    babel: {
      presets({ isServer }) {
        return [
          [
            require.resolve("@nuxt/babel-preset-app"),
            // require.resolve('@nuxt/babel-preset-app-edge'), // For nuxt-edge users
            {
              buildTarget: isServer ? "server" : "client",
              corejs: { version: 3 },
            },
          ],
          require.resolve("@babel/preset-typescript"),
        ];
      },
    },
  },`

I have a babel config 
`module.exports = {
  presets: ["@vue/app"],
};
`
If I commented the @vue/app the chart will work and the error will be gone. But of course the app will not work as before.

Anyone has the same experience?

**Comment by avarvouzou** [comment] 2022-03-18 14:28
any updates? I have exactly the same probelm @dncdrn @jankaderabek
