### ISSUE TITLE
fix: Runtime error: Legacy octal literals are not allowed in strict mode

### ISSUE THREAD

**Issue by Quineone** [nuxt-community/composition-api#142] opened 2020-07-03 07:30 UTC
**🐛 The bug**
```
Syntax Error: Legacy octal literals are not allowed in strict mode (566:23)
const staticPath = 'E:\1.2-rb2\1.7-subby\rb2-Subby-Template\Frontend\.nuxt\static-json';
```
**🛠️ To reproduce**
`yarn dev`
nuxt version `^2.13.0`

**Comment by danielroe** [comment] 2020-07-03 08:03
I think this is a duplicate of #137

**Closed** 2020-07-03 08:10 UTC
Labels: bug

**Comment by danielroe** [comment] 2020-07-14 12:47
This should now be fixed in v0.10.6. Let me know if it works for you 😃
