### ISSUE TITLE
help: I using useAsync. but error occured...

### ISSUE THREAD

**Issue by Retsuki** [nuxt-community/composition-api#269] opened 2020-10-15 03:13 UTC
**📚 What are you trying to do? Please describe.**
I want to get firestore data by useAsync.
but I can't get firestore data.

**🔍 What have you tried?**
I checked this document [https://composition-api.nuxtjs.org/useAsync](url)
and tried this code.

`

     const { app, params } = useContext()
     const supplier = useAsync(() => {
       return app.$firebase.firestore().collection('collection_name').doc(params.value.id).get()
         .then((doc: firebase.firestore.DocumentData) => {
           if (doc.exist) {
             const data = doc.data()
             data.supplierId = doc.id
             return data
           }
         })
     })

     return { supplier }

`

next error code

`

    Maximum call stack size exceeded

    Cannot stringify arbitrary non-POJOs DocumentReference (repeated 4 times)

`

if you know resolve to this problem, please tell me.
thanks.

**Comment by danielroe** [comment] 2020-10-15 06:52
The raw content of a Firebase response contains a circular reference, which can't be converted to JSON (which is necessary for passing the data from server to client). Make sure to extract just the data you need rather than returning the whole object from useAsync.

**Comment by Retsuki** [comment] 2020-10-15 07:57
> The raw content of a Firebase response contains a circular reference, which can't be converted to JSON (which is necessary for passing the data from server to client). Make sure to extract just the data you need rather than returning the whole object from useAsync.

thanks
Is this what you are saying??
`

    const supplier = useAsync(async () => {
        const documentRef = await app.$firebase.firestore().collection('aa_test').doc(params.value.id).get()
        const data = documentRef.data()
        return data.background_image
      })

`

**Comment by danielroe** [comment] 2020-10-15 13:02
@Retsuki Yes. :slightly_smiling_face:

**Comment by Retsuki** [comment] 2020-10-16 01:28
@danielroe But this code don't work. get the same error...

once the error is avoided with following code.

`
     
     const obj = reactive({
         background_image: ''
     })

     useAsync(() => {
      app.$firebase.firestore()
        .collection('aa_test').doc(params.value.id)
        .get()
        .then((doc: firebase.firestore.QueryDocumentSnapshot) => {
          const data = doc.data()

          obj.background_image = data.background_image
        })
    })

`

if you know of other solutions, please let me know🙇‍♀️

**Comment by danielroe** [comment] 2020-10-16 11:24
@Retsuki I think there must still be some kind of circular reference in `data.background_image`. You could test that theory by trying
```js
const supplier = useAsync(async () => {
  const documentRef = await app.$firebase.firestore().collection('aa_test').doc(params.value.id).get()
  const data = documentRef.data()

  return JSON.stringify(data.background_image) // just for testing
})
```

If that solves it, the issue is something to do with the kind of object that's being returned.

If it doesn't, I'd appreciate a repro via https://template.nuxtjs.org.

**Comment by danielroe** [comment] 2020-11-24 22:13
I'm closing this but you're welcome to provide more information and I'll happily look into it.

**Closed by danielroe** 2020-11-24 22:13 UTC
Labels: needs-repro
