### ISSUE TITLE
fix: 'computed value is readonly' error when using variable filled in useFetch

### ISSUE THREAD

**Issue by nicolashmln** [nuxt-community/composition-api#384] opened 2021-02-22 07:15 UTC
**🐛 The bug**
I fetch a `post` in the `useFetch` function and use its title in a `computedTitle` computed variable. On the first load there is the error `[Vue warn]: Write operation failed: computed value is readonly.`

**🛠️ To reproduce**
Here is the sandbox: https://codesandbox.io/s/vigilant-gould-45vg4

You can have a look in `/pages/posts/_id.vue` to see the `computedTitle` variable. I believe we can do that?

Note: when you go on an other post (without reloading the entire page) there is no error.

**🌈 Expected behaviour**
No error.

Thank you

**Comment by danielroe** [comment] 2021-02-22 07:29
Duplicate of #19.

**Closed** 2021-02-22 07:29 UTC
Labels: bug
